// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace NetrunnerChallenge.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201505231941109_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
