// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace NetrunnerChallenge.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210212299_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
